"""OpenAPI hash drift enforcement (BACKEND-140, re-pinned by addenda).

The accepted artifact hashes, path counts, and versions below are locked by
``Docs/03-contracts/OPENAPI-ACCEPTANCE.md`` — scaffold foundation plus the
2026-09-02 (G-E/G-G), 2026-09-04 (BACKEND-210), 2026-09-04b (BACKEND-211) and
2026-09-06 (product-v2 packets + A01/A09 additive reconciliation) addenda —
provenance ``scaffold-accepted``. Any content change to the exported snapshots
without regenerating ``PROVENANCE.json`` and creating a new acceptance record
fails these tests and reopens PS-05.

Line-ending provenance: the acceptance record hashes CRLF-encoded bytes. The
repository normalizes text to LF (``.gitattributes`` ``eol=lf``), so the
committed files hash differently while being byte-identical modulo line
endings. These tests hash the LF-canonical content and additionally prove that
re-encoding it with CRLF reproduces the accepted hashes exactly.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest

CONTRACTS_DIR = Path(__file__).resolve().parents[1] / "docs/contracts/openapi/current"

# Hashes exactly as recorded in OPENAPI-ACCEPTANCE.md and PROVENANCE.json
# (computed over CRLF-encoded bytes at acceptance time).
ACCEPTED = {
    "public-openapi.json": {
        "sha256": "469bd51ed7e1e0d3bed7c64affaf9d488c8ee124da69496e8f5b8acc36eda914",
        "paths": 49,
        "version": "0.4.0",
    },
    "admin-openapi.json": {
        "sha256": "274407a8fa3ad3b4b78c677bed76cc14871276468a70fb0d8542d0a637b1876b",
        "paths": 57,
        "version": "0.1.0",
    },
    "endpoint-inventory.md": {
        "sha256": "b4ca00dfa302130dd250211705637614b11e8761078b6f00fd2d160b581af166",
        "operations": 125,
    },
}

# Hashes of the same content with LF line endings (canonical repo form).
CANONICAL_LF = {
    "public-openapi.json": "2f95dd7e9e3cd9e7b2dc564eccb37e1d59a223dc96dc90a696fccec6ef926992",
    "admin-openapi.json": "e03cacb02df14b6be68b2ad6aa8c22b19467b3b3b2ace542a7f971f58000d3ed",
    "endpoint-inventory.md": "fbf7f80381223f6cb6fe7b6f467bce81e8bbd6787a17a541c3ff92fc47af4d4a",
}


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _provenance() -> dict:
    return json.loads((CONTRACTS_DIR / "PROVENANCE.json").read_text(encoding="utf-8"))


def _acceptance() -> dict:
    return json.loads((CONTRACTS_DIR / "ACCEPTANCE.json").read_text(encoding="utf-8"))


@pytest.mark.parametrize("filename", sorted(ACCEPTED))
def test_accepted_artifact_content_unchanged(filename):
    artifact = CONTRACTS_DIR / filename
    assert artifact.exists(), f"Accepted artifact missing: {artifact}"
    canonical = artifact.read_bytes().replace(b"\r\n", b"\n")
    assert _sha256(canonical) == CANONICAL_LF[filename], (
        f"{filename} drifted from the accepted content; reopen PS-05 per "
        "Docs/03-contracts/OPENAPI-ACCEPTANCE.md before adopting client types."
    )


@pytest.mark.parametrize("filename", sorted(ACCEPTED))
def test_canonical_content_reencodes_to_accepted_hash(filename):
    canonical = (CONTRACTS_DIR / filename).read_bytes().replace(b"\r\n", b"\n")
    crlf = canonical.replace(b"\n", b"\r\n")
    assert _sha256(crlf) == ACCEPTED[filename]["sha256"], (
        f"{filename} content no longer matches the accepted acceptance-record hash"
    )


@pytest.mark.parametrize("filename", ["public-openapi.json", "admin-openapi.json"])
def test_artifact_shape_matches_acceptance(filename):
    schema = json.loads((CONTRACTS_DIR / filename).read_text(encoding="utf-8"))
    accepted = ACCEPTED[filename]
    assert len(schema["paths"]) == accepted["paths"]
    assert schema["info"]["version"] == accepted["version"]


def test_provenance_matches_accepted_record():
    """Acceptance lives in the stable ACCEPTANCE.json record.

    PROVENANCE.json is regenerated by scripts/export_openapi.py on every run
    (fresh timestamp), so asserting acceptance status from it made
    identical-snapshot acceptance ambiguous. The stable record carries the
    scaffold-accepted status granted by Docs/03-contracts/OPENAPI-ACCEPTANCE.md.
    """
    acceptance = _acceptance()
    assert acceptance["status"] == "scaffold-accepted"
    assert acceptance["acceptanceRecord"].endswith("OPENAPI-ACCEPTANCE.md")
    assert re.fullmatch(r"[0-9a-f]{40}", acceptance["sourceCommit"])
    artifacts = acceptance["artifacts"]
    for filename, expected in ACCEPTED.items():
        recorded = artifacts[filename]
        assert recorded["sha256"] == expected["sha256"], filename
        for field in ("paths", "version", "operations"):
            if field in expected:
                assert recorded[field] == expected[field], filename


def test_provenance_is_generation_evidence_only():
    """PROVENANCE.json must never carry acceptance.

    The export tool rewrites it on every run, so any acceptance pointer inside
    it would be clobbered. Its artifact hashes must still equal the accepted
    record (linkage between generation evidence and acceptance).
    """
    provenance = _provenance()
    assert provenance["status"] == "source-generated-unaccepted"
    assert "acceptanceRecord" not in provenance
    acceptance = _acceptance()
    assert provenance["artifacts"] == acceptance["artifacts"]


def test_provenance_hash_matches_artifact_content():
    provenance = _provenance()
    for filename, recorded in provenance["artifacts"].items():
        canonical = (CONTRACTS_DIR / filename).read_bytes().replace(b"\r\n", b"\n")
        assert _sha256(canonical.replace(b"\n", b"\r\n")) == recorded["sha256"], filename
