# Generated by Django 5.2.9 on 2026-08-16 19:54
# DEBT-0003: historical RichTextField / wagtailimages refs replaced with
# TextField + media.Media so migrate works without the wagtail package.
# Production already applied the original operations; this source edit is
# for fresh installs and importability only (django_migrations rows unchanged).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'content_topic_tag',
                'ordering': ['locale', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='accessibility_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='license',
            field=models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='cc-by-nc-4', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ArticleSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('old_slug', models.SlugField(max_length=200)),
                ('new_slug', models.SlugField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_article_slug_redirect',
                'ordering': ['locale', 'old_slug'],
                'constraints': [models.UniqueConstraint(fields=('locale', 'old_slug'), name='content_article_slug_redirect_unique')],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'content_series',
                'ordering': ['locale', 'ordering', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='series_locale_slug_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_series_unique_locale_slug')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.series'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.topictag'),
        ),
    ]
