# Generated by Django 5.2.9 on 2026-08-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_p4_article_series_topictag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('research', 'Research'), ('engineering', 'Engineering'), ('ai', 'AI'), ('data', 'Data'), ('design', 'Design'), ('experiment', 'Experiment')], default='research', max_length=32)),
                ('objective', models.TextField(blank=True)),
                ('methods_summary', models.TextField(blank=True)),
                ('role', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('license', models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='cc-by-nc-4', max_length=32)),
                ('code_availability', models.CharField(choices=[('public', 'Public'), ('available_on_request', 'Available on request'), ('private', 'Private'), ('not_available', 'Not available'), ('not_applicable', 'Not applicable'), ('restricted', 'Restricted')], default='not_applicable', max_length=32)),
                ('data_availability', models.CharField(choices=[('public', 'Public'), ('available_on_request', 'Available on request'), ('private', 'Private'), ('not_available', 'Not available'), ('not_applicable', 'Not applicable'), ('restricted', 'Restricted')], default='not_applicable', max_length=32)),
                ('demo_availability', models.CharField(choices=[('public', 'Public'), ('available_on_request', 'Available on request'), ('private', 'Private'), ('not_available', 'Not available'), ('not_applicable', 'Not applicable'), ('restricted', 'Restricted')], default='not_applicable', max_length=32)),
                ('code_url', models.URLField(blank=True)),
                ('data_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'content_project',
                'ordering': ['locale', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('publication_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='content.project')),
            ],
            options={
                'db_table': 'content_project_collaborator',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('internal', 'Internal')], default='internal', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='content.project')),
            ],
            options={
                'db_table': 'content_project_evidence',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder', models.CharField(max_length=300)),
                ('grant_id', models.CharField(blank=True, max_length=200)),
                ('publication_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_items', to='content.project')),
            ],
            options={
                'db_table': 'content_project_funding',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('license', models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='cc-by-nc-4', max_length=32)),
                ('citation_count', models.PositiveIntegerField(blank=True, null=True)),
                ('citation_source', models.CharField(blank=True, max_length=300)),
                ('citation_last_verified', models.DateField(blank=True, null=True)),
                ('citation_visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('internal', 'Internal')], default='internal', max_length=20)),
            ],
            options={
                'db_table': 'content_publication',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='publication_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_publication_unique_locale_slug')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='projects', to='content.publication'),
        ),
        migrations.CreateModel(
            name='ResearchStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'content_research_statement',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='research_stmt_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_research_statement_unique_locale_slug')],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('problems', models.TextField(blank=True)),
                ('research_questions', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('future_directions', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'content_research_topic',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='research_topic_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_research_topic_unique_locale_slug')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='projects', to='content.researchtopic'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['locale', 'slug', 'status'], name='project_loc_slug_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='content_project_unique_locale_slug'),
        ),
    ]
