# Generated by Django 5.2.9 on 2026-08-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_p5_research_models'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCaseStudyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(choices=[('featured_case_study', 'Featured case study'), ('standard', 'Standard'), ('experiment', 'Experiment')], default='standard', max_length=32)),
                ('problem', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('technical_decisions', models.TextField(blank=True)),
                ('trade_offs', models.TextField(blank=True)),
                ('outcomes_summary', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('testing_summary', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='content.project')),
            ],
            options={
                'db_table': 'content_project_case_study_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('diagram_date', models.DateField()),
                ('alt_text', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('internal', 'Internal')], default='internal', max_length=20)),
                ('diagram_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='content.project')),
            ],
            options={
                'db_table': 'content_project_diagram',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('alt_text', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('internal', 'Internal')], default='internal', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='content.project')),
                ('screenshot_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'db_table': 'content_project_screenshot',
                'ordering': ['id'],
            },
        ),
    ]
