# Generated by Django 5.2.9 on 2026-08-18 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_profile_translation_state(apps, schema_editor):
    Profile = apps.get_model("content", "Profile")
    translation_keys: dict[str, uuid.UUID] = {}
    for profile in Profile.objects.order_by("slug", "locale", "id"):
        translation_key = translation_keys.setdefault(profile.slug, uuid.uuid4())
        profile.translation_key = translation_key
        if not profile.short_bio and profile.body:
            profile.short_bio = profile.body
        if not profile.long_bio and profile.body:
            profile.long_bio = profile.body
        profile.save(update_fields=["translation_key", "short_bio", "long_bio"])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_p6_case_study_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='long_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='translation_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='ProfileCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_entries', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_certificate',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('institution', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('gpa', models.CharField(blank=True, max_length=50)),
                ('thesis', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_education',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('organization', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('period', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_experience',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('status', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_entries', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_publication',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_research_project',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=300)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_skill',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='content.profile')),
            ],
            options={
                'db_table': 'content_profile_social_link',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.RunPython(
            backfill_profile_translation_state,
            migrations.RunPython.noop,
        ),
    ]
