# Generated by Django 5.2 on 2026-08-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composition", "0002_compositionpage_kind"),
        ("content", "0007_project_show_on_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_articles",
                to="composition.compositionpage",
            ),
        ),
    ]
