# Generated by Django 5.2.9 on 2026-08-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (('content', '0013_researchstatement_statement_pdf')),
        ('media', '0002_media_alt_text_en_media_alt_text_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='academic_stage',
            field=models.CharField(choices=[('preprint', 'Preprint'), ('in_press', 'In press'), ('published', 'Published'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='publication',
            name='access_state',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('metadata_only', 'Metadata only')], default='public', max_length=32),
        ),
        migrations.AddField(
            model_name='publication',
            name='accessibility_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='citation_text',
            field=models.TextField(blank=True, help_text='Editor-supplied citation export text only; never auto-fabricated.'),
        ),
        migrations.AddField(
            model_name='publication',
            name='code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='dataset_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='publication',
            name='preprint_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('journal', 'Journal article'), ('conference', 'Conference paper'), ('book_chapter', 'Book chapter'), ('manuscript', 'Manuscript'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('license', models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='all-rights-reserved', max_length=32)),
                ('access_state', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('metadata_only', 'Metadata only')], default='metadata_only', max_length=32)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'db_table': 'content_book',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='book_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_book_unique_locale_slug')],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('download_type', models.CharField(choices=[('pdf', 'PDF'), ('dataset', 'Dataset'), ('code', 'Code archive'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=32)),
                ('language', models.CharField(blank=True, help_text='Language of the file contents (fa/en/…), not CMS locale identity.', max_length=16)),
                ('access_state', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('metadata_only', 'Metadata only')], default='public', max_length=32)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('license', models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='all-rights-reserved', max_length=32)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.media')),
            ],
            options={
                'db_table': 'content_download',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='download_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_download_unique_locale_slug')],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('speakers', models.TextField(blank=True)),
                ('event_name', models.CharField(blank=True, max_length=300)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('abstract', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('slides_url', models.URLField(blank=True)),
                ('license', models.CharField(choices=[('cc-by-4', 'CC BY 4.0'), ('cc-by-nc-4', 'CC BY-NC 4.0'), ('all-rights-reserved', 'All Rights Reserved')], default='cc-by-nc-4', max_length=32)),
                ('access_state', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('metadata_only', 'Metadata only')], default='public', max_length=32)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('slides_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'db_table': 'content_talk',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='talk_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_talk_unique_locale_slug')],
            },
        ),
    ]
