# Generated by Django 5.2.9 on 2026-08-23 — P9 Teaching + Creative (Course/CreativeWork).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_p8_publications_books_talks_downloads"),
        ("media", "0002_media_alt_text_en_media_alt_text_fa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("scheduled", "Scheduled"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="draft", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("fa", "Persian"), ("en", "English")], db_index=True, max_length=2)),
                ("slug", models.SlugField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, help_text="Short summary for list cards.")),
                ("body", models.TextField(blank=True, help_text="Full description / syllabus (sanitized HTML).")),
                ("level", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced"), ("all_levels", "All levels")], default="beginner", max_length=32)),
                ("prerequisites", models.TextField(blank=True, help_text="Prerequisites; leave blank or 'none' for no prerequisites.")),
                ("outcomes", models.TextField(blank=True, help_text="Learning outcomes, one per line or prose.")),
                ("course_format", models.CharField(choices=[("online", "Online"), ("in_person", "In person"), ("hybrid", "Hybrid"), ("self_paced", "Self-paced"), ("workshop", "Workshop")], default="online", max_length=32)),
                ("course_language", models.CharField(choices=[("fa", "Persian"), ("en", "English"), ("bilingual", "Bilingual")], default="en", max_length=32)),
                ("availability", models.CharField(choices=[("public", "Public"), ("available_on_request", "Available on request"), ("private", "Private"), ("not_available", "Not available"), ("not_applicable", "Not applicable"), ("restricted", "Restricted")], default="public", max_length=32)),
                ("license", models.CharField(choices=[("cc-by-4", "CC BY 4.0"), ("cc-by-nc-4", "CC BY-NC 4.0"), ("all-rights-reserved", "All Rights Reserved")], default="cc-by-nc-4", max_length=32)),
                ("last_updated", models.DateField(blank=True, help_text="Required last-updated date.", null=True)),
                ("accessibility_notes", models.TextField(blank=True)),
                ("cover_media", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.media")),
            ],
            options={
                "db_table": "content_course",
                "ordering": ["locale", "slug"],
                "indexes": [models.Index(fields=["locale", "slug", "status"], name="course_loc_slug_st_idx")],
                "constraints": [models.UniqueConstraint(fields=("locale", "slug"), name="content_course_unique_locale_slug")],
            },
        ),
        migrations.CreateModel(
            name="CreativeWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("scheduled", "Scheduled"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="draft", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("fa", "Persian"), ("en", "English")], db_index=True, max_length=2)),
                ("slug", models.SlugField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, help_text="Short summary for list cards.")),
                ("body", models.TextField(blank=True, help_text="Full description (sanitized HTML).")),
                ("work_type", models.CharField(choices=[("design", "Design"), ("visual", "Visual"), ("photography", "Photography"), ("experiment", "Experiment"), ("other", "Other")], default="other", max_length=32)),
                ("creator_name", models.CharField(blank=True, help_text="Creator / author name.", max_length=200)),
                ("creator_role", models.CharField(blank=True, help_text="Role of the creator.", max_length=200)),
                ("creation_date", models.DateField(blank=True, help_text="Creation / publication date.", null=True)),
                ("license", models.CharField(choices=[("cc-by-4", "CC BY 4.0"), ("cc-by-nc-4", "CC BY-NC 4.0"), ("all-rights-reserved", "All Rights Reserved")], default="cc-by-nc-4", max_length=32)),
                ("access_state", models.CharField(choices=[("public", "Public"), ("restricted", "Restricted"), ("metadata_only", "Metadata only")], default="public", max_length=32)),
                ("rights_statement", models.TextField(blank=True, help_text="Rights / consent disclosure (no student PII).")),
                ("consent_verified", models.BooleanField(default=False, help_text="Rights / consent verified; no student PII stored.")),
                ("accessibility_notes", models.TextField(blank=True)),
                ("cover_media", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.media")),
            ],
            options={
                "db_table": "content_creative_work",
                "ordering": ["locale", "slug"],
                "indexes": [models.Index(fields=["locale", "slug", "status"], name="creative_work_loc_slug_st_idx")],
                "constraints": [models.UniqueConstraint(fields=("locale", "slug"), name="content_creative_work_unique_locale_slug")],
            },
        ),
        migrations.CreateModel(
            name="CreativeWorkGalleryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("alt_text", models.TextField(blank=True, help_text="Alt text (required for public projection).")),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("creative_work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery_images", to="content.creativework")),
                ("media", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.media")),
            ],
            options={
                "db_table": "content_creative_work_gallery_image",
                "ordering": ["ordering", "id"],
                "indexes": [models.Index(fields=["creative_work", "ordering"], name="cw_gallery_work_order_idx")],
            },
        ),
    ]
