# Generated by Django 5.2.9 on 2026-08-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_p9_courses_creativeworks'),
        ('media', '0002_media_alt_text_en_media_alt_text_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictag',
            name='description',
            field=models.TextField(blank=True, help_text='Glossary entry / editorial definition for the tag (shown on topic pages when present).'),
        ),
        migrations.AddField(
            model_name='topictag',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Comma-separated synonyms / aliases (not separate tags); creation must check this list.'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Summary for list cards / collection page.')),
                ('curator_name', models.CharField(blank=True, help_text='Human curator responsible for the collection (P10-03).', max_length=200)),
                ('curator_title', models.CharField(blank=True, help_text='Curator title / affiliation (optional).', max_length=200)),
                ('criteria', models.TextField(blank=True, help_text='Inclusion criteria prose — why members belong (P10-03).')),
                ('curated_date', models.DateField(blank=True, help_text='Date of last human curation review (P10-03).', null=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Curated articles (editorial only).', related_name='collections', to='content.article')),
                ('cover_media', models.ForeignKey(blank=True, help_text='Optional cover image (active Media only in public projection).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
                ('projects', models.ManyToManyField(blank=True, help_text='Curated projects (editorial only).', related_name='collections', to='content.project')),
                ('publications', models.ManyToManyField(blank=True, help_text='Curated publications (editorial only).', related_name='collections', to='content.publication')),
            ],
            options={
                'db_table': 'content_collection',
                'ordering': ['locale', 'slug'],
                'indexes': [models.Index(fields=['locale', 'slug', 'status'], name='collection_loc_slug_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_collection_unique_locale_slug')],
            },
        ),
    ]
