# Generated by Django 5.2.9 on 2026-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_collection_and_taxonomy_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('key', models.CharField(choices=[('identity', 'Identity'), ('graph', 'Graph'), ('research-fit', 'Research fit'), ('journey', 'Journey'), ('projects', 'Projects'), ('publications', 'Publications'), ('previews', 'Previews'), ('cta', 'Call to action')], max_length=32)),
                ('visible', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('selection_mode', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule'), ('hybrid', 'Hybrid')], default='manual', max_length=32)),
                ('provenance_note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'content_home_module',
                'ordering': ['locale', 'order'],
                'indexes': [models.Index(fields=['locale', 'status', 'visible'], name='home_module_loc_st_vis_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'key'), name='content_home_module_unique_locale_key')],
            },
        ),
    ]
