# Generated by Django 5.2.9 on 2026-08-27 18:15

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_home_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('type', models.CharField(choices=[('experience', 'Experience'), ('education', 'Education'), ('project', 'Project'), ('milestone', 'Milestone'), ('talk', 'Talk'), ('publication', 'Publication')], max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=300)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('detail_url', models.CharField(blank=True, max_length=300, validators=[apps.content.models.validate_detail_url])),
                ('order', models.PositiveIntegerField(default=1)),
                ('attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_records', to='content.profile')),
            ],
            options={
                'db_table': 'content_timeline_record',
                'ordering': ['locale', 'order', 'id'],
                'indexes': [models.Index(fields=['locale', 'order'], name='timeline_record_loc_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='content_timeline_record_order_gte_1')],
            },
        ),
    ]
