# Generated by Django 5.2.9 on 2026-08-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_timeline_records'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('color_role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'content_graph_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_graph_version',
                'ordering': ['locale', '-id'],
                'indexes': [models.Index(fields=['locale', 'status'], name='graph_version_loc_st_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('locale',), name='content_graph_version_unique_active_locale')],
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('accessible_label', models.CharField(blank=True, max_length=300)),
                ('color_role', models.CharField(max_length=100)),
                ('icon_role', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('pos_z', models.FloatField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='content.graphgroup')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='content.graphversion')),
            ],
            options={
                'db_table': 'content_graph_node',
                'ordering': ['version', 'node_id'],
            },
        ),
        migrations.AddField(
            model_name='graphgroup',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='content.graphversion'),
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('directed', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='content.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='content.graphnode')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='content.graphversion')),
            ],
            options={
                'db_table': 'content_graph_edge',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GraphNodeRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_records', to='content.graphnode')),
            ],
            options={
                'db_table': 'content_graph_node_related',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('node', 'content_type', 'object_id'), name='content_graph_node_related_unique_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('version', 'node_id'), name='content_graph_node_unique_version_node_id'),
        ),
        migrations.AddConstraint(
            model_name='graphedge',
            constraint=models.UniqueConstraint(fields=('version', 'source', 'target', 'relation_type'), name='content_graph_edge_unique_version_pair_rel'),
        ),
    ]
