# Generated by Django 5.2.9 on 2026-09-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_contentseedrecord'),
        ('media', '0003_media_presentation_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='book',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collection',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='collection',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='course',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creativework',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creativework',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creativework',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='creativework',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='creativework',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='download',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='download',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='download',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='download',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='landing',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='landing',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='publication',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='researchstatement',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchstatement',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='researchstatement',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='researchstatement',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='researchstatement',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='series',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='series',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='related_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talk',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='talk',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='talk',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='talk',
            name='translation_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='landing',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='landing',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
