# Generated by Django 5.2.9 on 2026-09-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_compositionpage_kind'),
        ('content', '0024_pu_creative_story'),
        ('media', '0003_media_presentation_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('translation_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_records', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='Short lesson summary.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.course')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_lessons', to='composition.compositionpage')),
            ],
            options={
                'db_table': 'content_lesson',
                'ordering': ['locale', 'course', 'position', 'slug'],
                'indexes': [models.Index(fields=['locale', 'course', 'status', 'position'], name='lesson_loc_crs_st_pos_idx'), models.Index(fields=['course', 'locale', 'slug'], name='lesson_crs_loc_slug_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'locale', 'slug'), name='content_lesson_unique_course_locale_slug')],
            },
        ),
    ]
