# Generated by Django 5.2.9 on 2026-09-05 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_compositionpage_kind'),
        ('content', '0027_pu_talk_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_downloads', to='composition.compositionpage'),
        ),
    ]
