# Generated by Django 5.2.9 on 2026-09-06 05:48

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_m2m_members(apps, schema_editor):
    Collection = apps.get_model('content', 'Collection')
    for collection in Collection.objects.all():
        if collection.members:
            continue
        members = []
        pos = 0
        for article in collection.articles.all().order_by('id'):
            members.append({'family': 'article', 'id': str(article.pk), 'position': pos})
            pos += 1
        for project in collection.projects.all().order_by('id'):
            members.append({'family': 'project', 'id': str(project.pk), 'position': pos})
            pos += 1
        for pub in collection.publications.all().order_by('id'):
            members.append({'family': 'publication', 'id': str(pub.pk), 'position': pos})
            pos += 1
        if members:
            collection.members = members
            collection.save(update_fields=['members'])


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_compositionpage_kind'),
        ('content', '0028_pu_resource_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='members',
            field=models.JSONField(blank=True, default=list, help_text='Ordered collection members: [{family, id, position}].'),
        ),
        migrations.AddField(
            model_name='collection',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_collections', to='composition.compositionpage'),
        ),
        migrations.RunPython(migrate_existing_m2m_members, reverse_code=migrations.RunPython.noop),
    ]
