# Generated by Django 5.2.9 on 2026-09-06 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_pu_series_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('locale', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('snapshot', models.JSONField(help_text='Complete published snapshot including parent fields, relations, and attached story.')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_publication_snapshot',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['entity_key', 'object_id', '-published_at'], name='content_pubsnap_ent_obj_pub'), models.Index(fields=['locale', 'slug'], name='content_pubsnap_locale_slug')],
            },
        ),
    ]
