# Generated by Django 5.2.17 on 2026-09-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_method'),
        ('media', '0003_media_presentation_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('translation_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_records', models.JSONField(blank=True, default=list)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'db_table': 'content_technology',
                'ordering': ['locale', 'sort_order', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='content_technology_unique_locale_slug')],
            },
        ),
    ]
