# Generated by Django 5.2.9 on 2026-08-18 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], db_index=True, max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['locale', 'status'], name='composition_locale_7d4663_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompositionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('1col', '1 col'), ('2col', '2 col'), ('3col', '3 col')], default='1col', max_length=8)),
                ('ratio', models.CharField(blank=True, default='', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='composition.compositionpage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CompositionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(max_length=32)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='composition.compositionsection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='compositionsection',
            constraint=models.UniqueConstraint(fields=('page', 'position'), name='uniq_section_position'),
        ),
        migrations.AddConstraint(
            model_name='compositionblock',
            constraint=models.UniqueConstraint(fields=('section', 'position'), name='uniq_block_position'),
        ),
    ]
