# Generated by Django 5.2 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositionpage",
            name="kind",
            field=models.CharField(
                choices=[("landing", "Landing"), ("story", "Story")],
                db_index=True,
                default="landing",
                max_length=16,
            ),
        ),
    ]
