# Generated by Django 5.2.17 on 2026-09-16 14:52

import apps.atlas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasNodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, validators=[apps.atlas.models.validate_taxonomy_key])),
                ('label_en', models.CharField(max_length=120)),
                ('label_fa', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('semantic_role', models.CharField(choices=[('anchor', 'Anchor'), ('area', 'Area'), ('record', 'Record'), ('utility', 'Utility')], max_length=16)),
                ('visual_role', models.CharField(choices=[('anchor', 'Anchor'), ('domain', 'Domain'), ('record', 'Record'), ('fine', 'Fine')], max_length=16)),
                ('default_importance', models.PositiveSmallIntegerField(default=50)),
                ('allow_as_root', models.BooleanField(default=False)),
                ('allow_children', models.BooleanField(default=True)),
                ('canonical_source', models.CharField(choices=[('research_topic', 'Research topic'), ('project', 'Project'), ('publication', 'Publication'), ('method', 'Method'), ('technology', 'Technology'), ('profile', 'Profile'), ('none', 'None')], default='none', max_length=32)),
                ('filter_visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'atlas_node_type',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AtlasRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, validators=[apps.atlas.models.validate_taxonomy_key])),
                ('label_en', models.CharField(max_length=120)),
                ('label_fa', models.CharField(max_length=120)),
                ('inverse_label_en', models.CharField(max_length=120)),
                ('inverse_label_fa', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('directed_default', models.BooleanField(default=True)),
                ('overridable_direction', models.BooleanField(default=False)),
                ('semantic_role', models.CharField(choices=[('anchor', 'Anchor'), ('area', 'Area'), ('record', 'Record'), ('utility', 'Utility')], max_length=16)),
                ('hierarchy_role', models.BooleanField(default=False)),
                ('default_weight', models.PositiveSmallIntegerField(default=1)),
                ('visual_priority', models.PositiveSmallIntegerField(default=50)),
                ('self_loop_policy', models.CharField(choices=[('forbid', 'Forbid'), ('allow', 'Allow')], default='forbid', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('allowed_source_types', models.ManyToManyField(blank=True, related_name='+', to='atlas.atlasnodetype')),
                ('allowed_target_types', models.ManyToManyField(blank=True, related_name='+', to='atlas.atlasnodetype')),
            ],
            options={
                'db_table': 'atlas_relation_type',
                'ordering': ['sort_order', 'key'],
            },
        ),
    ]
