# Generated by Django 5.2.17 on 2026-09-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('layout_revision', models.PositiveIntegerField(default=0)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='atlas.atlasversion')),
            ],
            options={
                'db_table': 'atlas_version',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AtlasNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.SlugField(max_length=80)),
                ('canonical_model', models.CharField(choices=[('research_topic', 'Research topic'), ('project', 'Project'), ('publication', 'Publication'), ('method', 'Method'), ('technology', 'Technology'), ('profile', 'Profile'), ('none', 'None')], default='none', max_length=32)),
                ('canonical_translation_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('importance', models.PositiveSmallIntegerField(default=50)),
                ('visible', models.BooleanField(default=True)),
                ('mobile_overview_priority', models.CharField(choices=[('auto', 'Auto'), ('featured', 'Featured'), ('hidden', 'Hidden')], default='auto', max_length=16)),
                ('pin_x', models.FloatField(blank=True, null=True)),
                ('pin_y', models.FloatField(blank=True, null=True)),
                ('pin_z', models.FloatField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='atlas.atlasnodetype')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='atlas.atlasversion')),
            ],
            options={
                'db_table': 'atlas_node',
                'ordering': ['version', 'sort_order', 'public_key'],
            },
        ),
        migrations.CreateModel(
            name='AtlasNodeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=2)),
                ('label_override', models.CharField(blank=True, max_length=200)),
                ('summary_override', models.TextField(blank=True)),
                ('accessible_label_override', models.CharField(blank=True, max_length=300)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='atlas.atlasnode')),
            ],
            options={
                'db_table': 'atlas_node_translation',
                'ordering': ['node', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('node', 'locale'), name='atlas_node_translation_unique_locale')],
            },
        ),
        migrations.AddConstraint(
            model_name='atlasversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='atlas_version_unique_active'),
        ),
        migrations.AddIndex(
            model_name='atlasnode',
            index=models.Index(fields=['version', 'visible'], name='atlas_node_version_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='atlasnode',
            index=models.Index(fields=['canonical_model', 'canonical_translation_key'], name='atlas_node_canonical_idx'),
        ),
        migrations.AddConstraint(
            model_name='atlasnode',
            constraint=models.UniqueConstraint(fields=('public_key',), name='atlas_node_unique_public_key'),
        ),
        migrations.AddConstraint(
            model_name='atlasnode',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_translation_key__isnull', False)), fields=('version', 'node_type', 'canonical_translation_key'), name='atlas_node_unique_canonical_per_version'),
        ),
    ]
