# Generated by Django 5.2.17 on 2026-09-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_version_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.SlugField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='atlas.atlasversion')),
            ],
            options={
                'db_table': 'atlas_group',
                'ordering': ['version', 'sort_order', 'public_key'],
            },
        ),
        migrations.CreateModel(
            name='AtlasGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='atlas.atlasgroup')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='atlas.atlasnode')),
            ],
            options={
                'db_table': 'atlas_group_membership',
                'ordering': ['group', 'sort_order', 'node'],
            },
        ),
        migrations.CreateModel(
            name='AtlasGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=2)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='atlas.atlasgroup')),
            ],
            options={
                'db_table': 'atlas_group_translation',
                'ordering': ['group', 'locale'],
            },
        ),
        migrations.CreateModel(
            name='AtlasRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directed', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='atlas.atlasrelationtype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='atlas.atlasnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='atlas.atlasnode')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='atlas.atlasversion')),
            ],
            options={
                'db_table': 'atlas_relation',
                'ordering': ['version', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtlasRelationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=2)),
                ('explanation', models.TextField(blank=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='atlas.atlasrelation')),
            ],
            options={
                'db_table': 'atlas_relation_translation',
                'ordering': ['relation', 'locale'],
            },
        ),
        migrations.AddConstraint(
            model_name='atlasgroup',
            constraint=models.UniqueConstraint(fields=('public_key',), name='atlas_group_unique_public_key'),
        ),
        migrations.AddConstraint(
            model_name='atlasgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'node'), name='atlas_group_membership_unique_node'),
        ),
        migrations.AddConstraint(
            model_name='atlasgrouptranslation',
            constraint=models.UniqueConstraint(fields=('group', 'locale'), name='atlas_group_translation_unique_locale'),
        ),
        migrations.AddConstraint(
            model_name='atlasrelation',
            constraint=models.UniqueConstraint(fields=('version', 'source', 'target', 'relation_type'), name='atlas_relation_unique_version_pair_rel'),
        ),
        migrations.AddConstraint(
            model_name='atlasrelationtranslation',
            constraint=models.UniqueConstraint(fields=('relation', 'locale'), name='atlas_relation_translation_unique_locale'),
        ),
    ]
