# Generated by Django 5.2.17 on 2026-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_relation_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atlasgroup',
            name='atlas_group_unique_public_key',
        ),
        migrations.RemoveConstraint(
            model_name='atlasnode',
            name='atlas_node_unique_public_key',
        ),
        migrations.AddConstraint(
            model_name='atlasgroup',
            constraint=models.UniqueConstraint(fields=('version', 'public_key'), name='atlas_group_version_public_key'),
        ),
        migrations.AddConstraint(
            model_name='atlasnode',
            constraint=models.UniqueConstraint(fields=('version', 'public_key'), name='atlas_node_version_public_key'),
        ),
    ]
