# Generated by Django 5.2.9 on 2026-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_entity', models.CharField(max_length=40)),
                ('target_slug', models.CharField(max_length=200)),
                ('locale', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Taha Mohammadi', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('primary_color', models.CharField(default='#1f2937', max_length=7)),
                ('nav_links', models.JSONField(blank=True, default=list)),
                ('seo_default_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_default_description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_key', models.CharField(default='default', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
