# Generated by Django 5.2.9 on 2026-08-15 21:42

import apps.media.storage
import apps.media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.media.storage.media_upload_path, validators=[apps.media.validators.validate_file_type, apps.media.validators.validate_file_size])),
                ('title', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, editable=False, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
