# Generated by Django 5.2.9 on 2026-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text_en',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='alt_text_fa',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
    ]
