# Generated by Django 5.2.9 on 2026-08-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_alt_text_en_media_alt_text_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='caption_en',
            field=models.CharField(blank=True, db_default='', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='media',
            name='caption_fa',
            field=models.CharField(blank=True, db_default='', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='media',
            name='focal_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='focal_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='rights_statement_en',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='rights_statement_fa',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='media.medialicense'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('focal_x__isnull', True), models.Q(('focal_x__gte', 0), ('focal_x__lte', 100)), _connector='OR'), name='media_media_focal_x_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('focal_y__isnull', True), models.Q(('focal_y__gte', 0), ('focal_y__lte', 100)), _connector='OR'), name='media_media_focal_y_percent_range'),
        ),
    ]
