# Generated by Django 5.2.9 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AggregateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Calendar date in UTC."
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical locale (fa/en).",
                        max_length=10,
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical frontend path.",
                        max_length=512,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        db_index=True,
                        help_text="Registered event type.",
                        max_length=64,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Registered action ID (never arbitrary text or URL).",
                        max_length=64,
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, help_text="Count of received events."
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "page_path", "event"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["date", "locale", "page_path", "event", "target"],
                        name="unique_daily_aggregate_event",
                    )
                ],
            },
        ),
    ]
