# Generated by Django 5.2.9 on 2026-09-06 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('requested_revision', models.CharField(blank=True, default='', max_length=255)),
                ('deployed_revision', models.CharField(blank=True, max_length=255, null=True)),
                ('affected_paths', models.JSONField(blank=True, default=list)),
                ('removal_state', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('effective', 'Effective'), ('failed', 'Failed')], default='not_requested', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'publication job',
                'verbose_name_plural': 'publication jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationMachineNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'publication machine nonce',
                'verbose_name_plural': 'publication machine nonces',
            },
        ),
    ]
