# Generated by Django 5.2.9 on 2026-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebuild', '0001_publication_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationjob',
            name='revoked_paths',
            field=models.JSONField(blank=True, default=list, help_text='A01: detail/file URLs actually denied at the edge on archive. Never includes shared pages (home, list indexes); those are only rebuilt via affected_paths.'),
        ),
    ]
